// <auto-generated />
using System;
using ManageTaskAssignment.Assignment.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageTaskAssignment.Assignment.Api.Migrations
{
    [DbContext(typeof(WorkOrderDbContext))]
    [Migration("20220822152845_Initials")]
    partial class Initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManageTaskAssignment.Assignment.Api.Entities.Models.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00be01a1-5cd2-49fc-8bb1-c2f967ae8c85"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblWorkOrders", "workOrder");
                });

            modelBuilder.Entity("ManageTaskAssignment.Assignment.Api.Entities.Models.WorkOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("8452ac27-3902-4d6d-80a7-1bf7dd9bfaaa"));

                    b.Property<string>("DetailsOfTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("tblWorkOrderDetails", "workOrder");
                });

            modelBuilder.Entity("ManageTaskAssignment.Assignment.Api.Entities.Models.WorkOrderDetail", b =>
                {
                    b.HasOne("ManageTaskAssignment.Assignment.Api.Entities.Models.WorkOrder", "WorkOrder")
                        .WithOne("WorkOrderDetail")
                        .HasForeignKey("ManageTaskAssignment.Assignment.Api.Entities.Models.WorkOrderDetail", "WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("ManageTaskAssignment.Assignment.Api.Entities.Models.WorkOrder", b =>
                {
                    b.Navigation("WorkOrderDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
